version: '2'
services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf-prod.d/:/etc/nginx/conf.d


  nginx-gen:
    volumes:
      - ./nginx/conf-prod.d/nginx.tmpl:/etc/docker-gen/nginx.tmpl
