version: '2'

volumes:
  xibodata:
    external: true

networks:
  front:
    external: true
  back:
    external: true

services:
  nginx:
    container_name: nginx
    build: nginx
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
      - ./nginx/local:/var/www
      - xibodata:/var/www/xibo:ro
    ports:
      - "80:80"
    networks:
      - front
      - back

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    command: "-notify-sighup nginx -watch /etc/docker-gen/nginx.tmpl /etc/nginx/conf.d/default.conf"
    networks:
      - front
